### ISSUE TITLE
BOM is missing

### ISSUE THREAD

**Issue by montyx99** [AchimPieters/CNC-Mini-Laser-Engraver#1]
Hello,
First of all I appreciate your awesome job.
I cannot find the referenced blog entry on your site about this CNC laser engraver machine. (There is a link in the readme.md to your site.) So I think that the BoM list was shown there. Can you upload the BoM here please?
I mostly looking for the Y stepper motor that you use.
Thanks

**Comment by AchimPieters** [comment]
@montyx99 I just finished the blog, but did not planned it yet to air. But here's the hardware list:

Hardware
Arduino Nano.
2 x DVR8825 Stepper motor driver.
2 x DVD drive stepper mechanis.
1 x IRFZ44N N-CHANNEL MOSFET.
1 x LM7805 Voltage regulator (with Heat-sink).
1 x 47Ω resistor.
1 x 10kΩ resistor.
1 x 1000μF16V capacitor.
1 x 250mW Laser with adjustable lens (or above).
1 x 12v 2Amps power supply minimum
8 x small neodymium magnets
Laser Safety Glasses!

**Comment by montyx99** [comment]
Thanks a lot!
